FORMAT: 1A

# Insight Inc. Burger Bar 
This API was built to familirize ourselves with apiary.io and 

# Group Burger Bar
Burger Bar related resources of the **Insight Inc. Burger Bar API**

## Burger Components [/api/index.php/]
### List all Meats [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]



## Indivdual Components [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
